#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail
IFS=$'\n\t'
trap ctrl_c 2

 	R='\033[1;31m'
        G='\033[1;32m'
        Y='\033[1;33m'
        B='\033[1;34m'
        M='\033[1;35m'
        C='\033[1;36m'
        W='\033[0m'


	clear
	echo -e "$R ____  _                  _"
	echo -e "| __ )(_)_ __   __ _ _ __(_) ___  ___     __  __"
	echo -e "|  _ \| | '_ \ / _  |  __| |/ _ \/ __|____\ \/ /"
	echo -e "| |_) | | | | | (_| | |  | | (_) \__ \_____>  <"
	echo -e "|____/|_|_| |_|\__,_|_|  |_|\___/|___/    /_/\_"
	echo -e "       $B Cesar Hacker The Gray"
	echo
	printf "$Y"
	echo -e "$C   [1] $Y viruz.apk            $C [2] $Y binario"
	echo -e "$C   [3] $Y cadena bina..        $C [4] $Y conjela-grupos"
	echo -e "$C   [5] $Y +Nota                $C [6] $Y Contacta a Cesar"
	echo -e "$C   [10] $R Salir $B"
	echo
	echo


	while read -p "Que binario quieres?  >> " SIGN && [ -z $SIGN ]; do
		printf "$R
		[Cesar🐿] Porfavor escribe un numero valido
		\n $W"
	done


	if [ $SIGN -eq '1' ]; then
		echo
		printf "$C [Gray]$G Generando Viruz app$W \n"
		echo
		echo
		cd $PREFIX/bin/modulos
                sleep 3
		cp $PREFIX/bin/modulos/Gray1.jpg /sdcard
		mv /sdcard/Gray1.jpg /sdcard/viruz.apk
		echo
		printf "$G \n \t Listoo Ahora esta en tu memoria interna!!"
		echo
		printf "$C presiona en $G enter $C para continuar"
		echo
		read enter
		binarios

		
	elif [ $SIGN -eq '2' ]; then
		printf "$C [Gray]$G Creando binario $Y \n"
		echo
		echo
		cd $PREFIX/bin//modulos
		sleep 3
		cat $PREFIX/bin/modulos/Gray2.jpg
		echo
		printf "$G \n \t Listo!!"
		echo
		printf "$C Presiona en $G enter $C para continuar"
		echo
		read enter
		binarios

		
	elif [ $SIGN -eq '3' ]; then
		printf "$C [Gray] $G Creando cadena-bina..$Y \\n"
		echo
		echo
		cd $PREFIX/bin/modulos
		sleep 3
		cat $PREFIX/bin/modulos/Gray3.jpg
		echo
		printf "$G \n \t Listo!!"
		echo
		printf "$C presiona en $G enter $C para continuar"
		echo
		read enter
		binarios

		
	elif [ $SIGN -eq '4' ]; then
		printf "$C generando un conjelador $Y \\n"
		echo
		echo
		cd $PREFIX/bin/modulos
		sleep 5
		cat $PREFIX/bin/modulos/Cesar.jpg
		echo
		printf "$G \n \t Listo!!"
		echo
		printf "$C presiona en $G enter $C para regresar"
		echo
		read enter
		binarios
	
	
	elif [ $SIGN -eq '5' ]; then
		printf "$C Estrayendo Nota $Y \\n"
		echo
		echo
		cd $PREFIX/bin/modulos
		sleep 2
		bash $PREFIX/bin/modulos/Gray10.jpg
		echo
		printf "$G \n \t Listoo!!"
		echo
		printf "$C presiona en $G enter $C para regresar"
		echo
		read enter
		binarios

	
	elif [ $SIGN -eq '6' ]; then
		printf "$C Espera contactando a Cesar \\n"
		echo
		echo
		cd $PREFIX/bin/modulos
		sleep 5
		bash $PREFIX/bin/modulos/Grayy.jpg
		echo
		printf "$G \n \t Listoo!!"
		echo
		printf "$C presiona en $G enter $C para continuar"
		read enter
		echo
		binarios

	elif [ $SIGN -eq '10' ]; then
	        echo
		echo
		printf "$C Grasias por usar mi herramienta \\n"
		echo
		echo
		printf "$C Atentamente Cesar \\n"
		echo
		echo


	else
	       bash $PREFIX/bin/binarios

       fi
